### ISSUE TITLE
Help with item IDs

### ISSUE THREAD

**Issue by CatgirlChilis** [NexAdn/UnitedShops#30]
Is there a place where I could find A list of the IDs this plugin uses? (or something like it?)

I'm looking for the IDs of Dark oak and acacia logs, the stripped log IDs, the bark and stripped bark IDs, and Piston IDs.

**Comment by NexAdn** [comment]
These are Bukkit Material types. In many cases they are equal to the standard Minecraft ID equivalent (e.g. “STONE” is “minecraft:stone”), but sometimes they are different. This is due to the nature that these Material names exist longer than named item IDs in minecraft (i.e. way before Minecraft 1.7), but as Mojang implemented named item IDs, they didn't care what names have already been used. That's why some of them are different from the Minecraft ID. In most cases though, you should be fine by just inserting the Minecraft IDs (without “minecraft.“ and with Capslock). If my plugin is unable to find an ID, it will tell you on startup which one it couldn't find.

Additionally, there are so-called “damage” or “durability” values. They are used for 1. specifying a durability for a tool/weapon/... (well... that one was obvious) and 2. specifying subordinate properties for an item (e.g. all wool blocks have the ID “WOOL”/“minecraft:wool” and the damage value indicates the color). Stone for example has Diorite, Granite and Andesite with the same ID, but different damage values. Different sorts of wood also share the same ID, but different damage values. You can see these values by enabling `F3+H` in minecraft and hovering over an item. It will show you a numeric ID followed by a slash and the damage value (which is per default 0 for most items). If you want to know how to write these in the configuration files, see the Wiki.

If you somehow encounter that you cannot use the minecraft IDs, because Bukkit's ones are different, this [1] page gives you a list of all Bukkit Material names (but without further explanation, but most names should be self-explanatory).

[1] https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by CatgirlChilis** [comment]
I get that much, F3+H and the list have been my main sources, But there are some that aren't the same on either. For example, according to the list and F3+H, An oak log is OAK_LOG, but that is not recognized by the plugin. it's actually LOG:0 - LOG:3 for the fist 4 logs, and then something else for Acacia and Dark oak.

Same thing with the stripped logs, STRIPPED_OAK_LOG, But that doesn't work. (I don't know what does)

**Comment by NexAdn** [comment]
https://www.reddit.com/r/admincraft/comments/5kew9g/is_there_a_translation_guide_somewhere_between/

This one might help you. One of the reply contains a table to translate most Minecraft IDs to Bukkit Material names.

But, as this question is not related to my plugin in any kind but the fact, that it uses Bukkit's naming conventions to parse item types, I'll lock this conversation.
